[modules]
autoload=no

load => res_pjproject.so
load => res_pjsip.so
load => chan_pjsip.so
load => chan_quectel.so
load => res_rtp_asterisk.so
load => bridge_simple.so
load => codec_ulaw.so
load => codec_alaw.so
load => res_timing_pthread.so
load => pbx_config.so
load => app_dial.so
load => app_system.so
load => app_verbose.so
